### --- Day 3: No Matter How You Slice It ---
The Elves managed to locate the chimney-squeeze prototype fabric for Santa's suit (thanks to someone who helpfully wrote its box IDs on the wall of the warehouse in the middle of the night). Unfortunately, anomalies are still affecting them - nobody can even agree on how to cut the fabric.

The whole piece of fabric they're working on is a very large square - at least 1000 inches on each side.

Each Elf has made a claim about which area of fabric would be ideal for Santa's suit. All claims have an ID and consist of a single rectangle with edges parallel to the edges of the fabric. Each claim's rectangle is defined as follows:

 - The number of inches between the left edge of the fabric and the left edge of the rectangle.  
 - The number of inches between the top edge of the fabric and the top edge of the rectangle.  
 - The width of the rectangle in inches.  
 - The height of the rectangle in inches.  
A claim like `#123 @ 3,2: 5x4` means that claim ID 123 specifies a rectangle 3 inches from the left edge, 2 inches from the top edge, 5 inches wide, and 4 inches tall. Visually, it claims the square inches of fabric represented by `#` (and ignores the square inches of fabric represented by `.`) in the diagram below:
```
...........
...........
...#####...
...#####...
...#####...
...#####...
...........
...........
...........
```
The problem is that many of the claims overlap, causing two or more claims to cover part of the same areas. For example, consider the following claims:

 - `#1 @ 1,3: 4x4`
 - `#2 @ 3,1: 4x4`
 - `#3 @ 5,5: 2x2`  
Visually, these claim the following areas:
```
........
...2222.
...2222.
.11XX22.
.11XX22.
.111133.
.111133.
........
```
The four square inches marked with X are claimed by both 1 and 2. (Claim 3, while adjacent to the others, does not overlap either of them.)


If the Elves all proceed with their own plans, none of them will have enough fabric. **How many square inches of fabric are within two or more claims?**

In [298]:
import numpy as np
# Read in file
xx = []
with open('sed_out.txt', 'r') as f:
    xx = [(int(a), int(b), int(c), int(d) for x.split()) for x in f]
#     for line in f:
        
#     xx.append(f.read().strip().split())
xx
# xx = np.array(xx).astype(np.int).reshape((int(len(xx[0])/4), 4))
# xx[:, 2] = np.add(xx[:, 0], xx[:, 2])
# xx[:, 3] = np.add(xx[:, 1], xx[:, 3])
# #     arr = np.zeros((xx[:, 3].max(), xx[:, 2].max()))
# arr = np.zeros((1000, 1000))
# for l, t, x, y in xx.tolist():
#     arr[t:y, l:x] += 1
# print(len(arr[arr>=2]))

SyntaxError: invalid syntax (<ipython-input-298-bc36da68974e>, line 5)

In [22]:
import numpy as np
import pandas as pd
df = pd.read_csv('/Users/Alex/projects/adventofcode_2018/03/sed_out.txt', header=None, sep='\s+')
df[2] = df[0].values + df[2].values
df[3] = df[1].values + df[3].values
arr = np.zeros((1000, 1000))
for l, t, x, y in df.values.tolist():
    print(l, t, x, y)
    break
    arr[t:y, l:x] += 1
print(len(arr[arr>1]))

342 645 367 665
0


In [27]:
def run3():
    import sys, re
    import numpy as np
    pattern = re.compile( R'#(?P<pid>\d+) @ (?P<x>\d+),(?P<y>\d+): (?P<w>\d+)x(?P<h>\d+)')
    arr = np.zeros((1000, 1000))
    for line in open('input.txt').readlines():
        if not line.strip(): continue
        m = pattern.match(line)
    #    pid = int(m.group('pid'))
        x = int(m.group('x'))
        y = int(m.group('y'))
#         w = int(m.group('w')) + x
#         h = int(m.group('h')) + y
    #    print(x, y, h, w)
    #    break
        arr[y:int(m.group('h')) + y, x:int(m.group('w')) + x] +=1
    return len(arr[arr>1])

In [28]:
%lprun -f run3 run3()

In [30]:
%%timeit
run3()

37.5 ms ± 2.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [80]:
def run2():
    import numpy as np
    import pandas as pd
    df = pd.read_csv('sed_out.txt', header=None, delim_whitespace=True, dtype={0:'u2',1:'u2',2:'u2',3:'u2'})
    df[2] = df[0].values + df[2].values
    df[3] = df[1].values + df[3].values
    arr = np.zeros((1000, 1000))
    for l, t, x, y in df.values.tolist():
        arr[t:y, l:x] += 1
    return len(arr[arr>1])

In [81]:
run2()

116491

In [82]:
%lprun -f run2 run2()

In [84]:
%%timeit
run2()

31.3 ms ± 1.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [270]:
def run_da_thing(file):
    import numpy as np
    # Read in file
    xx = []
    with open(file, 'r') as f:
        xx.append(f.read().strip().split())
    xx = np.array(xx).astype(np.int).reshape((int(len(xx[0])/4), 4))

    xx[:, 2] = np.add(xx[:, 0], xx[:, 2])
    xx[:, 3] = np.add(xx[:, 1], xx[:, 3])
#     arr = np.zeros((xx[:, 3].max(), xx[:, 2].max()))
    arr = np.zeros((1000, 1000))
    for l, t, x, y in xx.tolist():
        arr[t:y, l:x] += 1
    return len(arr[arr>=2])

In [296]:
xx = []
with open('sed_out.txt', 'r') as f:
    xx.append(f.read().strip().split('\n'))
xx = xx[0]
xx

['342 645 25 20',
 '124 968 28 19',
 '680 765 26 20',
 '832 699 12 15',
 '4 746 29 14',
 '926 115 19 17',
 '662 587 28 12',
 '532 568 27 23',
 '860 23 16 21',
 '530 562 12 27',
 '15 254 10 27',
 '375 611 18 10',
 '357 389 22 23',
 '483 392 14 16',
 '426 705 17 13',
 '273 918 23 28',
 '873 722 13 13',
 '429 749 12 25',
 '701 937 14 11',
 '89 231 23 26',
 '704 220 10 27',
 '481 847 21 24',
 '9 378 14 19',
 '682 442 10 21',
 '242 63 21 23',
 '748 871 20 13',
 '784 338 25 25',
 '966 669 20 20',
 '589 833 22 25',
 '489 489 16 24',
 '976 478 4 4',
 '739 826 13 15',
 '783 753 21 17',
 '433 367 22 11',
 '32 841 10 20',
 '258 497 26 28',
 '632 776 18 25',
 '517 389 20 14',
 '446 740 19 26',
 '667 455 15 14',
 '664 252 25 26',
 '227 45 29 21',
 '127 138 29 27',
 '466 308 19 17',
 '356 134 12 19',
 '609 640 28 24',
 '677 228 16 27',
 '149 610 10 28',
 '863 498 21 28',
 '913 511 12 27',
 '748 761 24 11',
 '802 288 10 22',
 '26 442 29 20',
 '85 464 20 21',
 '262 944 21 18',
 '876 753 15 10',
 '105 

In [271]:
run_da_thing('sed_out.txt')

116491

In [272]:
%%timeit
run_da_thing('sed_out.txt')

31.7 ms ± 583 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [273]:
%lprun -f run_da_thing run_da_thing('sed_out.txt')

In [327]:
%%timeit
import pandas as pd
df = pd.read_csv('/Users/Alex/projects/adventofcode_2018/03/sed_out.txt', header=None, sep='\s+')

3.94 ms ± 639 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [329]:
df.head()

0    1   2   3
0  342  645  25  20
1  124  968  28  19
2  680  765  26  20
3  832  699  12  15
4    4  746  29  14

In [315]:
%%timeit
claims = []
with open('sed_out.txt', 'r') as f:
    claims = [x.strip().split() for x in f]

1.41 ms ± 31.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [316]:
claims

['342 645 25 20',
 '124 968 28 19',
 '680 765 26 20',
 '832 699 12 15',
 '4 746 29 14',
 '926 115 19 17',
 '662 587 28 12',
 '532 568 27 23',
 '860 23 16 21',
 '530 562 12 27',
 '15 254 10 27',
 '375 611 18 10',
 '357 389 22 23',
 '483 392 14 16',
 '426 705 17 13',
 '273 918 23 28',
 '873 722 13 13',
 '429 749 12 25',
 '701 937 14 11',
 '89 231 23 26',
 '704 220 10 27',
 '481 847 21 24',
 '9 378 14 19',
 '682 442 10 21',
 '242 63 21 23',
 '748 871 20 13',
 '784 338 25 25',
 '966 669 20 20',
 '589 833 22 25',
 '489 489 16 24',
 '976 478 4 4',
 '739 826 13 15',
 '783 753 21 17',
 '433 367 22 11',
 '32 841 10 20',
 '258 497 26 28',
 '632 776 18 25',
 '517 389 20 14',
 '446 740 19 26',
 '667 455 15 14',
 '664 252 25 26',
 '227 45 29 21',
 '127 138 29 27',
 '466 308 19 17',
 '356 134 12 19',
 '609 640 28 24',
 '677 228 16 27',
 '149 610 10 28',
 '863 498 21 28',
 '913 511 12 27',
 '748 761 24 11',
 '802 288 10 22',
 '26 442 29 20',
 '85 464 20 21',
 '262 944 21 18',
 '876 753 15 10',
 '105 

In [193]:
%%timeit
data = np.genfromtxt('sed_out.txt')

12 ms ± 204 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [213]:
%%timeit
with open('sed_out.txt', 'r') as f:
    data = np.fromfile(f, dtype=np.int)

97.3 µs ± 2.52 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [215]:
with open('sed_out.txt', 'r') as f:
    data = np.fromfile(f, dtype=np.int)
data

array([2320818590052398131, 3616683177870898482, 4049334440759468084, ...,
       3688790181197068042, 3893985516243595552, 3611949797526746161])

In [195]:
data = np.genfromtxt('sed_out.txt')
data

array([[342., 645.,  25.,  20.],
       [124., 968.,  28.,  19.],
       [680., 765.,  26.,  20.],
       ...,
       [792., 736.,  24.,  27.],
       [731., 713.,  17.,  27.],
       [614., 449.,  22.,  20.]])

In [153]:
import re
reg = re.compile(r'#.*\s@\s(\d+),(\d+):\s(\d+)x(\d+)')
claims = []
with open('input.txt', 'r') as f:
    claims.append(f.read().strip())
print(np.array([x for x in (reg.findall(s) for s in claims)]).astype(np.int)[0])
# np.array(reg.findall(xyz)).astype('int')

[[342 645  25  20]
 [124 968  28  19]
 [680 765  26  20]
 ...
 [792 736  24  27]
 [731 713  17  27]
 [614 449  22  20]]


In [178]:
yy = np.zeros((4,4))
yy

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [179]:
np.add.at(yy, ([0,0], [3,3]), 1)
yy

array([[0., 0., 0., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [183]:
test

['#1 @ 1,3: 4x4', '#2 @ 3,1: 4x4', '#3 @ 5,5: 2x2']

In [184]:
test = ['#1 @ 1,3: 4x4', '#2 @ 3,1: 4x4', '#3 @ 5,5: 2x2']
xx = np.array([x[0] for x in (re.findall(r'#.*\s@\s(\d+),(\d+):\s(\d+)x(\d+)', s) for s in test)]).astype(np.int)
xx[:, 2] = np.add(xx[:, 0], xx[:, 2])
xx[:, 3] = np.add(xx[:, 1], xx[:, 3])
xx

array([[1, 3, 5, 7],
       [3, 1, 7, 5],
       [5, 5, 7, 7]])

In [92]:
def overlapping_blocks(coords, x, y, n):
    # Init zeros of minimum size
    arr = np.zeros((y, x))
    for l, t, x, y in coords:
        arr[t:y, l:x] += 1
    return len(arr[arr>=n])

In [84]:
xx

array([[342., 645., 367.,  20.],
       [124., 968., 152.,  19.],
       [680., 765., 706.,  20.],
       ...,
       [792., 736., 816.,  27.],
       [731., 713., 748.,  27.],
       [614., 449., 636.,  20.]])

In [33]:
# imports
import re
import pandas as pd
import numpy as np
# make a DataFrame because it's what I know
df = pd.DataFrame([x[0] for x in (re.findall(r'(#.*)\s@\s(\d+),(\d+):\s(\d+)x(\d+)', s) for s in test)], 
                  columns=['id', 'left', 'top', 'width', 'height'])
# Make pd.Series numeric
for c in ['left', 'top', 'width', 'height']:
    df[c] = pd.to_numeric(df[c])
# Get right and bottom bounds
df['x'] = df['left'] + df['width']
df['y'] = df['top'] + df['height']
x = df.x.max()
y = df.y.max()
# Back to np...
xx = df[['left', 'top', 'x', 'y']].values.tolist()
# n-dimensional array of zeros
arr = np.zeros((y, x))
# add one at all claimed coords
for l, t, x, y in xx:
    arr[t:y, l:x] += 1
# number of points greater than or equal to 2
print(len(arr[np.where(arr>=2)]))

4


In [1]:
%load_ext line_profiler

In [41]:
%lprun -f overlapping_blocks overlapping_blocks(xx, x, y, 2)

In [42]:
%%timeit
overlapping_blocks(xx, x, y, 2)

44.8 µs ± 1.28 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%%timeit
arr = np.zeros((y, x))
a = [np.ones((y, x))[t:y, l:x] ]

In [314]:
a = np.zeros((9000, 9000))
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#1 @ 1,3: 4x4
#2 @ 3,1: 4x4
#3 @ 5,5: 2x2

In [35]:
a.add.at(a, [3:7,1:3])

SyntaxError: invalid syntax (<ipython-input-35-9828288a3b71>, line 1)

In [34]:
xx[0]

[1, 3, 5, 7]

### --- Part Two ---
Amidst the chaos, you notice that exactly one claim doesn't overlap by even a single square inch of fabric with any other claim. If you can somehow draw attention to it, maybe the Elves will be able to make Santa's suit after all!

For example, in the claims above, only claim 3 is intact after all claims are made.

**What is the ID of the only claim that doesn't overlap?**

In [10]:
coords1, coords2 = zip(*[([l, l, x, x], [t, y, y, t]) for l, t, x, y in xx])

In [15]:
from bokeh.plotting import figure, show, ColumnDataSource
from bokeh.models import HoverTool
from bokeh.io import output_notebook

output_notebook()
p = figure(plot_width=980)
p.patches(list(coords1), list(coords2),
          color="red", alpha=0.1, line_width=0)

show(p)

Loading BokehJS ...

In [11]:
df[df['left'].eq(654) & df['y'].eq(185) & df['x'].eq(668)]

id  left  top  width  height    x    y
706  #707   654  158     14      27  668  185